### ISSUE TITLE
Erro ao Executar Comando para Instalação do Portal Padrão na Versão Mais Recente do Linux

### ISSUE THREAD

**Issue by marcosmartins1989** [plonegovbr/portal.buildout#43]
Ao executar o comando de instalação python bootstrap.py -c buildout.cfg ocorre o seguinte erro, sendo com isso impedido de prosseguir com a instalação do Portal Padrão.

(py27) plone@plone:~/portal.buildout$ python bootstrap.py -c buildout.cfg
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-19.6.zip
Extracting in /tmp/tmp7KwaRI
Now working in /tmp/tmp7KwaRI/setuptools-19.6
Building a Setuptools egg in /tmp/bootstrap-EzbTS7
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-EzbTS7/setuptools-19.6-py2.7.egg
Traceback (most recent call last):
  File "bootstrap.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 132, in _do_download
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/extern/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 48, in <module>
  File "/opt/plone/portal.buildout/py27/local/lib/python2.7/site-packages/pkg_resources/extern/**init**.py", line 43, in load_module
    mod = sys.modules[extant]
AttributeError: 'NoneType' object has no attribute 'modules

Conforme foi solicitado no grupo para abrir um relato do ocorrido aqui no Github, aproveito e deixo a solução me passada para resolver o ocorrido:

cd /opt/plone/portal.buildout
rm -rf py27
virtualenv --no-setuptools py27
source py27/bin/activate
python bootstrap.py -c buildout.cfg

e continue o manual.

**Comment by idgserpro** [comment]
@marcosmartins1989 favor informar a versão do python e do virtualenv.

**Comment by marcosmartins1989** [comment]
A versão do Python é 2.7.6 e do Virtualenv é 14.0.1

**Comment by idgserpro** [comment]
https://github.com/plonegovbr/portal.buildout/pull/42

**Comment by whereiswr** [comment]
@marcosmartins1989, olá! Eu passei pelo mesmo problema que você contou, daí optei por usar o [`pyenv`](https://github.com/yyuu/pyenv), então consegui executar os processos de [_buildout_](https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/producao/#buildout) e de [inicialização e controle](https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/producao/#inicializacao-e-controle) corretamente numa máquina com Ubuntu 14.04 LTS.

Para isso, instalei o `pyenv` usando o _script_ [`pyenv-installer`](https://github.com/yyuu/pyenv-installer). Depois, instalei a versão 2.7.0 do Python usando o comando `pyenv install 2.7`. Em seguida, criei um `virtualenv` chamado de `portalpadrao-py2.7` e ativei-o usando os comandos  `pyenv virtualenv 2.7 portalpadrao-py2.7` e `pyenv activate portalpadrao-py2.7` respectivamente. Antes de fazer o _buildout_, baixei e instalei a dependência `threadedframe` manualmente (leia [essa discussão](https://colab.interlegis.leg.br/archives/thread/plonegov-br/instalacao-error-couldnt-find-a-distribution-for-threadframe02) e baixe [desse site](https://majid.info/blog/threadframe-multithreaded-stack-frame-extraction-for-python/)). Por fim, executei sei problemas:

```
python bootstrap.py -c buildout.cfg
./bin/buildout -c buildout.cfg
./bin/supervisord
./bin/supervisorctl status
```

Espero que lhe ajude! :wink:

**Comment by idgserpro** [comment]
@marcosmartins1989 alguma novidade no problema?

**Comment by marcosmartins1989** [comment]
Olá @idgserpro,

Depois disso eu consegui instalar o Portal Padrão diversas vezes, pois isso foi preciso. Lembro na época que era um problema na virtualenv, de depois disso até o Manual de Instalação foi modificado, e sendo possível instalar o Portal Padrão seguindo-o sem maiores problemas.
Eu encontrei problemas recentemente para atualizar para a versão 1.5.1, dá erro nas seguintes linhas do base.cfg:
zcml =
    ${buildout:zcml}
Eu cheguei comentar essas linhas, aí ele atualiza mais não sobem as instance1 e instance2 depois disso...

**Comment by idgserpro** [comment]
@marcosmartins1989 tem como testar o 1.1.5.2? Pessoas tiveram erros parecidos com o seu de não subir a instância mas isso foi consertado em https://github.com/plonegovbr/portal.buildout/commit/8e64d8aabb0cdc93b20dc190fb10cc2bb0ae0956.

**Comment by marcosmartins1989** [comment]
Olá @idgserpro,

Eu fiz as modificações necessárias no arquivo buildout.d/base.cfg e desta vez atualizou para a versão 1.1.5.2 sem dar nenhum problema. 

Obrigado pela atenção

Att
